FROM secretflow/secretflow-lite-anolis8:1.10.0b1

RUN yum install -y time

WORKDIR /root

ADD source ./

# RUN time ./mult3.py 1 2 3
# RUN time ./innerprod.py 10
# RUN time ./xtabs.py 10
# RUN time ./xtabs_jax.py 10
# RUN time ./cmp.py 10
