name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    build:
        name: Build containers for modified frameworks
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v3
          - name: Get changed files
            id: changed-files
            uses: tj-actions/changed-files@v41.0.1
            with:
              dir_names: "true"
          - name: test changed files
            run: echo ${{ steps.changed-files.outputs.all_changed_files }}

          - name: Build the Docker image
            run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)