name: Build and test the Docker container for MP-SPDZ

on:
  push:
    branches: [ master ]
    paths:
      - mp-spdz/*
  pull_request:
    branches: [ master ]
    paths:
      - mp-spdz/*

jobs:
    build:
        name: Build container for MP-SPDZ
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v3
          - uses: docker/setup-buildx-action@v2
          - uses: docker/build-push-action@v4
            with:
              context: mp-spdz
              tags: mp-spdz
              load: true
              cache-from: type=gha
              cache-to: type=gha,mode=max
              push: false
