name: Build and test the Docker container for SCALE-Mamba

on:
  push:
    branches: [ master ]
    paths:
      - scalemamba/*
  pull_request:
    branches: [ master ]
    paths:
      - scalemamba/*

jobs:
    build:
        name: Build container for SCALE-Mamba
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v3
          - uses: docker/setup-buildx-action@v2
          - uses: docker/build-push-action@v4
            with:
              context: scalemamba
              tags: scalemamba
              load: true
              cache-from: type=gha
              cache-to: type=gha,mode=max
              push: false
