name: Build and test the Docker container for ABY

on:
  push:
    branches: [ master ]
    paths:
      - aby/*
  pull_request:
    branches: [ master ]

jobs:
    build:
        name: Build container for ABY
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v3
          - uses: docker/setup-buildx-action@v2
          - uses: docker/build-push-action@v4
            with:
              context: aby
              tags: aby
              load: true
              cache-from: type=gha
              cache-to: type=gha,mode=max
              push: false
