name: Build and test the Docker container for Jiff

on:
  push:
    branches: [ master ]
    paths:
      - jiff/*
  pull_request:
    branches: [ master ]

jobs:
    build:
        name: Build container for Jiff
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v3
          - uses: docker/setup-buildx-action@v2
          - uses: docker/build-push-action@v4
            with:
              context: jiff
              tags: jiff
              load: true
              cache-from: type=gha
              cache-to: type=gha,mode=max
              push: false
