name: Build and test the Docker container for MPyC

on:
  push:
    branches: [ master ]
    paths:
      - mpyc/*
  pull_request:
    branches: [ master ]
    paths:
      - mpyc/*

jobs:
    build:
        name: Build container for MPyC
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v3
          - uses: docker/setup-buildx-action@v2
          - uses: docker/build-push-action@v4
            with:
              context: mpyc
              tags: mpyc
              load: true
              cache-from: type=gha
              cache-to: type=gha,mode=max
              push: false
