name: Build and test the Docker container for ABY3

on:
  push:
    branches: [ master ]
    paths:
      - aby3/*
  pull_request:
    branches: [ master ]
    paths:
      - aby3/*

jobs:
    build:
        name: Build container for ABY3
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v3
          - uses: docker/setup-buildx-action@v2
          - uses: docker/build-push-action@v4
            with:
              context: aby3
              tags: aby3
              load: true
              cache-from: type=gha
              cache-to: type=gha,mode=max
              push: false
